### ISSUE TITLE
missing cat.autopgen-diacritics-vells.bin

### ISSUE THREAD

**Issue by OlaFosheimGrostad** [apertium/apertium-cat#25]
Output from trying to build apertium-eng-cat
```
make: *** No rule to make target `/Users/username/apertium/share/apertium/apertium-cat/cat.autopgen-diacritics-vells.bin', needed by `eng-cat.autopgen-diacritics-vells.bin'.  Stop.
```

**Comment by MarcRiera** [comment]
Hello, are you building the master branch of `apertium-eng-cat` on a fairly recent commit? Postgeneration for diacritics was migrated to a new preferences-based system back in 2021, and all pairs using Catalan were modified accordingly. Here is the relevant commit for the English-Catalan pair: https://github.com/apertium/apertium-eng-cat/commit/551b1eb00609d82cc6243dfe519e5b10c1ab4a9f

If you had pulled and built the repos previously, you may need to rerun `./autogen.sh` for English, Catalan and English-Catalan after `git pull` and before running `make`.
